[package]
name = "cargo-sovax"
version = "0.1.7"
authors.workspace = true
edition.workspace = true
description = "Cargo subcommand for scaffolding and running Sova apps"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://s00d.github.io/sova/guide/cargo-sovax"
readme = "README.md"
keywords = ["sova", "cargo-subcommand", "web", "scaffold"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
include = [
  "src/**/*",
  "templates/**/*",
  "README.md",
  "Cargo.toml",
  "LICENSE",
]

[[bin]]
name = "cargo-sovax"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
include_dir = { workspace = true }
notify = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true, features = ["parse", "display"] }
ctrlc = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
