[package]
name = "auth"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "auth"
path = "src/main.rs"

[dependencies]
ruvo = { workspace = true, features = ["session", "cookies"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde_json = { workspace = true }
