[package]
name = "templates_i18n"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "templates_i18n"
path = "src/main.rs"

[dependencies]
ruvo = { path = "../../../crates/ruvo", features = ["i18n", "templates"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json = "1"
