[package]
name = "sova-templates"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
description = "Template engine plugin for Sova"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/sova-templates"
readme = "README.md"
keywords = ["http", "web", "framework", "async"]
categories = ["web-programming::http-server", "network-programming"]

[dependencies]
sova-core = { workspace = true }
minijinja = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
minijinja-autoreload = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tempfile = { workspace = true }
http = { workspace = true }
