[package]
name = "sova-cookies"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
description = "Cookie parsing plugin for Sova"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/sova-cookies"
readme = "README.md"
keywords = ["http", "web", "framework", "async"]
categories = ["web-programming::http-server", "network-programming"]

[dependencies]
sova-core = { workspace = true }
cookie = { workspace = true, features = ["percent-encode"] }
http = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
cookie = { workspace = true, features = ["percent-encode"] }
