[package]
name = "raw_echo"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "raw_echo"
path = "src/main.rs"

[dependencies]
sova = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde_json = { workspace = true }
bytes = { workspace = true }
hyper = { workspace = true, features = ["server", "http1"] }
http-body-util = { workspace = true }
