[package]
name = "api_jwt"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "api_jwt"
path = "src/main.rs"

[dependencies]
ruvo = { workspace = true, features = ["passport-jwt", "env", "cli"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
