[package]
name = "sova-shield"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
description = "Security headers middleware for Sova"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/sova-shield"
readme = "README.md"
keywords = ["http", "web", "framework", "async"]
categories = ["web-programming::http-server", "network-programming"]

[dependencies]
sova-core = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
http = { workspace = true }
