// Generated by sova-docs-gen — do not edit.
export const pluginsNav = [
  { text: 'Catalog', link: '/plugins/' },
  {
    text: 'HTTP & middleware',
    items: [
    { text: 'acme', link: '/plugins/acme' },
    { text: 'compress', link: '/plugins/compress' },
    { text: 'cookies', link: '/plugins/cookies' },
    { text: 'cors', link: '/plugins/cors' },
    { text: 'csrf', link: '/plugins/csrf' },
    { text: 'env', link: '/plugins/env' },
    { text: 'idempotency', link: '/plugins/idempotency' },
    { text: 'rate-limit', link: '/plugins/rate-limit' },
    { text: 'response-cache', link: '/plugins/response-cache' },
    { text: 'shield', link: '/plugins/shield' },
    { text: 'static', link: '/plugins/static' }
    ],
  },
  {
    text: 'Auth & validation',
    items: [
    { text: 'auth', link: '/plugins/auth' },
    { text: 'passport', link: '/plugins/passport' },
    { text: 'session', link: '/plugins/session' },
    { text: 'vld', link: '/plugins/vld' }
    ],
  },
  {
    text: 'Data & jobs',
    items: [
    { text: 'db', link: '/plugins/db' },
    { text: 'fs', link: '/plugins/fs' },
    { text: 'redis', link: '/plugins/redis' },
    { text: 'storage', link: '/plugins/storage' },
    { text: 'store', link: '/plugins/store' },
    { text: 'tasks', link: '/plugins/tasks' },
    { text: 'tasks-store', link: '/plugins/tasks-store' }
    ],
  },
  {
    text: 'Content & mail',
    items: [
    { text: 'i18n', link: '/plugins/i18n' },
    { text: 'mail', link: '/plugins/mail' },
    { text: 'meta', link: '/plugins/meta' },
    { text: 'openapi', link: '/plugins/openapi' },
    { text: 'templates', link: '/plugins/templates' }
    ],
  },
  {
    text: 'Realtime',
    items: [
    { text: 'notifications', link: '/plugins/notifications' },
    { text: 'quic', link: '/plugins/quic' },
    { text: 'sse', link: '/plugins/sse' },
    { text: 'udp', link: '/plugins/udp' },
    { text: 'ws', link: '/plugins/ws' }
    ],
  },
  {
    text: 'Observability',
    items: [
    { text: 'activity', link: '/plugins/activity' },
    { text: 'devtools', link: '/plugins/devtools' },
    { text: 'observability', link: '/plugins/observability' }
    ],
  },
  {
    text: 'Integrations',
    items: [
    { text: 'ai', link: '/plugins/ai' },
    { text: 'http', link: '/plugins/http' }
    ],
  },
  {
    text: 'Tooling',
    items: [
    { text: 'cli', link: '/plugins/cli' }
    ],
  }
] as const

export const pluginsSidebar = [
  { text: 'Catalog', link: '/plugins/' },
  {
    text: 'HTTP & middleware',
    collapsed: false,
    items: [
    { text: 'acme', link: '/plugins/acme' },
    { text: 'compress', link: '/plugins/compress' },
    { text: 'cookies', link: '/plugins/cookies' },
    { text: 'cors', link: '/plugins/cors' },
    { text: 'csrf', link: '/plugins/csrf' },
    { text: 'env', link: '/plugins/env' },
    { text: 'idempotency', link: '/plugins/idempotency' },
    { text: 'rate-limit', link: '/plugins/rate-limit' },
    { text: 'response-cache', link: '/plugins/response-cache' },
    { text: 'shield', link: '/plugins/shield' },
    { text: 'static', link: '/plugins/static' }
    ],
  },
  {
    text: 'Auth & validation',
    collapsed: false,
    items: [
    { text: 'auth', link: '/plugins/auth' },
    { text: 'passport', link: '/plugins/passport' },
    { text: 'session', link: '/plugins/session' },
    { text: 'vld', link: '/plugins/vld' }
    ],
  },
  {
    text: 'Data & jobs',
    collapsed: false,
    items: [
    { text: 'db', link: '/plugins/db' },
    { text: 'fs', link: '/plugins/fs' },
    { text: 'redis', link: '/plugins/redis' },
    { text: 'storage', link: '/plugins/storage' },
    { text: 'store', link: '/plugins/store' },
    { text: 'tasks', link: '/plugins/tasks' },
    { text: 'tasks-store', link: '/plugins/tasks-store' }
    ],
  },
  {
    text: 'Content & mail',
    collapsed: false,
    items: [
    { text: 'i18n', link: '/plugins/i18n' },
    { text: 'mail', link: '/plugins/mail' },
    { text: 'meta', link: '/plugins/meta' },
    { text: 'openapi', link: '/plugins/openapi' },
    { text: 'templates', link: '/plugins/templates' }
    ],
  },
  {
    text: 'Realtime',
    collapsed: false,
    items: [
    { text: 'notifications', link: '/plugins/notifications' },
    { text: 'quic', link: '/plugins/quic' },
    { text: 'sse', link: '/plugins/sse' },
    { text: 'udp', link: '/plugins/udp' },
    { text: 'ws', link: '/plugins/ws' }
    ],
  },
  {
    text: 'Observability',
    collapsed: false,
    items: [
    { text: 'activity', link: '/plugins/activity' },
    { text: 'devtools', link: '/plugins/devtools' },
    { text: 'observability', link: '/plugins/observability' }
    ],
  },
  {
    text: 'Integrations',
    collapsed: false,
    items: [
    { text: 'ai', link: '/plugins/ai' },
    { text: 'http', link: '/plugins/http' }
    ],
  },
  {
    text: 'Tooling',
    collapsed: false,
    items: [
    { text: 'cli', link: '/plugins/cli' }
    ],
  }
]
