// Generated by sova-docs-gen — do not edit.
export const pluginSdkNav = [
  { text: 'Index', link: '/api/plugin-sdk' },
  { text: 'Overview', link: '/api/plugin-sdk/overview' },
  { text: 'Plugin trait', link: '/api/plugin-sdk/plugin-trait' },
  { text: 'Middleware', link: '/api/plugin-sdk/middleware' },
  { text: 'State & dependencies', link: '/api/plugin-sdk/state' },
  { text: 'Config', link: '/api/plugin-sdk/config' },
  { text: 'Lifecycle & services', link: '/api/plugin-sdk/lifecycle' },
  { text: 'Checks & CLI', link: '/api/plugin-sdk/checks-cli' },
  { text: 'Routes & introspection', link: '/api/plugin-sdk/routes' },
  { text: 'Extractors & Problem+', link: '/api/plugin-sdk/extractors' },
  { text: 'Events', link: '/api/plugin-sdk/events' },
  { text: 'HTML & log hooks', link: '/api/plugin-sdk/html-hooks' },
  { text: 'Errors', link: '/api/plugin-sdk/errors' },
  { text: 'Recipes', link: '/api/plugin-sdk/recipes' },
  { text: 'extend API', link: '/api/plugin-sdk/extend-api' },
  { text: 'Testing', link: '/api/plugin-sdk/testing' }
] as const

export const pluginSdkSidebar = [
  { text: 'Plugin SDK', link: '/api/plugin-sdk' },
  {
    text: 'Start',
    collapsed: false,
    items: [
    { text: 'Overview', link: '/api/plugin-sdk/overview' },
    { text: 'Plugin trait', link: '/api/plugin-sdk/plugin-trait' }
    ],
  },
  {
    text: 'Cookbook',
    collapsed: false,
    items: [
    { text: 'Middleware', link: '/api/plugin-sdk/middleware' },
    { text: 'State & dependencies', link: '/api/plugin-sdk/state' },
    { text: 'Config', link: '/api/plugin-sdk/config' },
    { text: 'Lifecycle & services', link: '/api/plugin-sdk/lifecycle' },
    { text: 'Checks & CLI', link: '/api/plugin-sdk/checks-cli' },
    { text: 'Routes & introspection', link: '/api/plugin-sdk/routes' },
    { text: 'Extractors & Problem+', link: '/api/plugin-sdk/extractors' },
    { text: 'Events', link: '/api/plugin-sdk/events' },
    { text: 'HTML & log hooks', link: '/api/plugin-sdk/html-hooks' },
    { text: 'Errors', link: '/api/plugin-sdk/errors' }
    ],
  },
  {
    text: 'Patterns',
    collapsed: false,
    items: [
    { text: 'Recipes', link: '/api/plugin-sdk/recipes' }
    ],
  },
  {
    text: 'Reference',
    collapsed: false,
    items: [
    { text: 'extend API', link: '/api/plugin-sdk/extend-api' },
    { text: 'Testing', link: '/api/plugin-sdk/testing' }
    ],
  }
]
