[package]
name = "api_preset"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "api_preset"
path = "src/main.rs"

[dependencies]
sova = { workspace = true, features = ["api"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
