[package]
name = "sovax"
version = "0.1.2"
authors.workspace = true
edition.workspace = true
description = "CLI ServerArgs / listen_args for Sova (local dev)"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/sovax"
readme = "README.md"
keywords = ["http", "web", "framework", "async", "cli"]
categories = ["web-programming::http-server", "command-line-interface"]

[dependencies]
sova-core = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
clap = { workspace = true, features = ["derive", "env"] }
