[package]
name = "tls_hello"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "tls_hello"
path = "src/main.rs"

[dependencies]
sova = { workspace = true, features = ["dev-tls", "cors"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde_json = { workspace = true }
