[package]
name = "storage_demo"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "storage_demo"
path = "src/main.rs"

[dependencies]
sova = { workspace = true, features = ["cli", "env", "storage", "storage-s3", "storage-memory"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
